### ISSUE TITLE
7688 DUO 網頁控制

### ISSUE THREAD

**Issue by bnm890** [loveiu516/loveiu516.github.io#1]
你好,請問目前我在7688 DUO /www 資料夾內放了網頁
但是要怎麼樣才能使我燒入到7688 DUO的Arduino 程式上傳溫度到網頁內??

**Comment by loveiu516** [comment]
使用node.js 透過
SerialPort("/dev/ttyS0", {
baudrate: 57600
});

與Arduino通訊
https://github.com/loveiu516/loveiu516.github.io/blob/master/7688DUO_power.js
請參考

2016-12-16 17:06 GMT+08:00 bnm890 <notifications@github.com>:
